/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "BuildTest"

include(
	"common-custom-user-data-gradle-plugin", 
	"foojay-toolchains.foojay-resolver", 
	"gradle-build-scan-quickstart", 
	"maven_java_web_example", 
	"WaveMaker_Training_ToDo_App",
	 "leave_management_portal"	
)

 


