/*
 * This file was generated by the Gradle "init" task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-library")
    id("maven-publish")
}

repositories {
    mavenLocal()
    mavenCentral() 
}

dependencies {
    api("org.codehaus.jackson:jackson-mapper-asl:1.9.13")
    api("mysql:mysql-connector-java:8.0.23")
    testImplementation("junit:junit:4.13.2")
    compileOnly("javax.servlet:javax.servlet-api:4.0.1")
}


group = "api"
version = "0.0.1-SNAPSHOT"
description = "api"
// java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

tasks.withType<JavaCompile> {
    sourceCompatibility = "17"
    targetCompatibility = "17"
    options.encoding = "UTF-8"
}
